name: Scheduled Sync

on:
  schedule:
    - cron: "0 3,5,7,9,11,13,15 * * *"

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl -X POST https://ca.vercel.app/api/run \
          -H "Content-Type: application/json" \
          -d '{"token":"${{ secrets.ADMIN_TOKEN }}"}'
