name: Scheduled Sync

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl -X POST https://ca-gules.vercel.app/api/scheduled \
          -H "Content-Type: application/json" \
          -d '{"token":"${{ secrets.ADMIN_TOKEN }}"}'
